# Generated by Django 3.1.7 on 2021-03-16 17:42

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_works', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicworks',
            name='contributors',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), size=None), size=None),
        ),
    ]
