# Generated by Django 3.1.7 on 2021-03-16 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_works', '0002_auto_20210316_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicworks',
            name='contributors',
            field=models.CharField(max_length=300),
        ),
    ]
