# Generated by Django 3.1.7 on 2021-03-16 18:51

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_works', '0003_auto_20210316_1746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musicworks',
            name='contributors',
        ),
        migrations.AddField(
            model_name='musicworks',
            name='contrubutors',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), default=list, size=None),
        ),
    ]
