# Generated by Django 3.1.7 on 2021-03-16 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_works', '0004_auto_20210316_1851'),
    ]

    operations = [
        migrations.RenameField(
            model_name='musicworks',
            old_name='contrubutors',
            new_name='contributors',
        ),
    ]
