# Generated by Django 3.1.7 on 2021-03-17 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_works', '0005_auto_20210316_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicworks',
            name='iswc',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
